### ISSUE TITLE
Game not opening on NixOS

### ISSUE THREAD

**Issue by ljubitje** [FixAkaTheFix/Tower-Pixel-Dungeon#8]
Hi! I am very excited to test your game as I like the genre you're taking the SPD towards.
Unfortunately the game does not start on my system.

OS: NixOS 24.11

Java (test 1):
openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-nixos)
OpenJDK 64-Bit Server VM (build 21.0.4+7-nixos, mixed mode)

Java (test 2):
openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-nixos)
OpenJDK 64-Bit Server VM (build 17.0.12+7-nixos, mixed mode)

I tried it with two java versions, but got the same error every time.

The command I ran was:
`java -jar desktop-0.3.2.jar`

Output was:
```
java.lang.NoClassDefFoundError: sun/misc/Unsafe
        at org.lwjgl.system.MemoryUtil.getUnsafeInstance(MemoryUtil.java:2948)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:112)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
        at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:84)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
        at com.towerpixel.towerpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:175)
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 7 more


Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
```

Thanks and kind regards, Klemen

**Comment by FixAkaTheFix** [comment]
So you have downloaded the newest source code, and using it to make a jar file to test does not work? Does the normal, non-debug release launch without issues?
1. If the answer is yes to both questions (release -jar files launch the game without problems but the source one does not) then it is most likely due to commits being half-working. I am making commits every time I do anything (like literally anything, even if it is makes the app stop working). The current source code may not be usable as it contains coding errors due to this exact reason.
2. If both the release and the source code versions do not launch, it is, as far as I know, because of this command not working for this sort of apps (you can google that NoClassDefFoundError appears after bad commands, classpath). For example, any fork of shattered creates .jar archives through `desktop:release` gradle command, not through `java -jar`
Please specify, are you trying to test the newest source code, or if the game does not launch at all, whichever, release .jars or self-compiled .jars, you are trying to open

**Comment by ljubitje** [comment]
I apologise for not being clear.
I tested the release version.
When running just `java desktop-0.3.2.jar` I get:
```
Error: Could not find or load main class desktop-0.3.2.jar
Caused by: java.lang.ClassNotFoundException: desktop-0.3.2.jar
```
Is there a specific version of java this is known to work or not work with?

**Comment by FixAkaTheFix** [comment]
Ok, it is much more clear now
The main classes in libgdx, the framework PDs run on, has its own issues and may not simply be run by usual means. 
https://stackoverflow.com/questions/26482449/libgdx-desktop-launcher-error-main-class-not-found
This is similar to what you have sent: main class not found error. I checked several other cases when this exception could appear, and due to there being no Kotlin classes the link above might be the solution.
And no, as far as I am aware, ShPD framework supports older versions of java, has low API level etc... so the error appears due to lack of commands.
Also, a question: do shattered pd jar archives launch as usual, or those are also broken?
If even this solution won't be effective, I suppose the code will work if used through intellij directly. Like, compile the source code through it with the desktop:debug gradle command; the save files will remain intact if you close the intellij-launched app.
Best regards,
Fix

**Comment by ljubitje** [comment]
Jar release of regular ShPD has the same problem.
I couldn't help myself with the link you sent; I don't understand what it is telling me related to this case, so I didn't know what to do with it.

However, I installed different libraries of java (openjdk8-bootstrap, openjdk11-boostrap, and openjdk17, all separately) and am now getting:
```
[LWJGL] GLFW_PLATFORM_UNAVAILABLE error
        Description : Failed to detect any supported platform
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1047)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:88)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
                com.towerpixel.towerpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:175)
com.badlogic.gdx.utils.GdxRuntimeException: Unable to initialize GLFW
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:89)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
        at com.towerpixel.towerpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:175)



missing software! (we will try basic console input)
 ___________
/           \ 
| tiny file |
|  dialogs  |
\_____  ____/
      \|
tiny file dialogs on UNIX needs:
   applescript or kdialog or yad or Xdialog
or zenity (or matedialog or shellementary or qarma)
or python (2 or 3) + tkinter + python-dbus (optional)
or dialog (opens console if needed)
or xterm + bash (opens console for basic input)
or existing console for basic input


Pixel Towers Has Crashed!

Pixel Towers has run into an error it cannot recover from and has crashed, sorry about that!

If you could, please email this error message to the developer (Evan@ShatteredPixel.com):

version: 0.3.2
utils.GdxRuntimeException: Unable to initialize GLFW
    at backends.lwjgl3.Lwjgl3Application.initializeGlfw(89)
    at backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(219)
    at desktop.DesktopLauncher.main(175)


press enter to continue
```
Do I lack some dependencies?

I don't want to use IntelliJ as an app launcher.
Ideally the TPD would be available directly from Flathub and from nixkpkgs repo.
Till then I would like to solve this at least to run via terminal with a normal command, so simple that I can share it with my non-tech friends.

**Comment by ljubitje** [comment]
Now I tried with jdk and jre8, separately.
The error I am now getting is:
```
[LWJGL] GLFW_API_UNAVAILABLE error
        Description : GLX: Failed to load GLX
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:520)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
                com.towerpixel.towerpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:185)
[GAME] com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
        at com.towerpixel.towerpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:185)



missing software! (we will try basic console input)
 ___________
/           \ 
| tiny file |
|  dialogs  |
\_____  ____/
      \|
tiny file dialogs on UNIX needs:
   applescript or kdialog or yad or Xdialog
or zenity (or matedialog or shellementary or qarma)
or python (2 or 3) + tkinter + python-dbus (optional)
or dialog (opens console if needed)
or xterm + bash (opens console for basic input)
or existing console for basic input


Pixel Towers Has Crashed!

Pixel Towers was not able to initialize its graphics display, sorry about that!

This usually happens when your graphics card does not support OpenGL 2.0+, or has misconfigured graphics drivers.

If you are certain the game should be working on your computer, feel free to message the developer (Evan@ShatteredPixel.com)

version: 0.3.2

press enter to continue 
```

**Comment by FixAkaTheFix** [comment]
Update your integrated graphics driver, that is the issue. This error appears when you don't have or haven't updated your driver for your graphics card. For example AMD drivers, Nvidia (GEForce) drivers etc., depending on what your graphics card is.

**Comment by ljubitje** [comment]
My drivers are updated. I think the problem may be NixOS not being designed to run simple apps without wrappers.

**Comment by FixAkaTheFix** [comment]
https://mynixos.com/nixpkgs/package/tower-pixel-dungeon
Found that. Might be a somewhat maintained version for NixOS!

**Comment by ljubitje** [comment]
I swear it wasn't there when we were first talking!
Anyhow.. Brilliant! Thanks a lot for pointing me to it!
